### PR TITLE
don't force UUID usage on queries client side; use psql instead

### PR DESCRIPTION
**Pull request by no-reply**
this guard prevents applications from querying valid existing ids--leading to `ObjectNotFound` errors when objects exist in the DB backend.

### CODE REVIEW

**Comment by no-reply** [comment]
i did a first pass on this with `#with_sql`, but decided that was too injection-ish. `Sequel.lit` with the `?` placeholder pattern safely escapes the input variables: https://sequel.jeremyevans.net/rdoc/files/doc/security_rdoc.html#label-Manually+Created+Literal+Strings

it looks quite a bit nicer, too.

**Comment by jrochkind** [comment]
Would you need to adjust this one as well? https://github.com/samvera-labs/valkyrie-sequel/blob/4894ddde1227323b7666c1f1b12d6cdd29fe6b69/lib/valkyrie/sequel/resource_factory/resource_converter.rb#L26

If you do, then I think the `ACCEPTABLE_UUID` constant would be un-referenced, and should also be removed?

**Comment by no-reply** [comment]
@jrochkind:

> Would you need to adjust this one as well? 

good catch.

> If you do, then I think the ACCEPTABLE_UUID constant would be un-referenced, and should also be removed?

removing the constant is going to be breaking for downstream users, so i left it out here.

**Review by tpendragon — APPROVED** [review]

**Comment by tpendragon** [comment]
Looks good to me. I want to give @jrochkind a chance to look over the PR before I merge, though.

**Comment by jrochkind** [comment]
Oh no need to wait on me, I just sometimes get curious to see what's going on and then try to be helpful if I think I have something helpful to contribute, but do not need or want the responsibility for approval; I don't currently use valkyrie.  Thanks though!

**Pull request merged**
